const fs = require("fs");

// Test case data: [key, module, title, type, priority, status, preconditions, steps[], expected]
const cases = [
  // MODULE A
  ["ZTM-3","A","A1-TC01: Successful account opening with valid details","functional","P1","ready","User is on the ZincBank sign-up page and does not already have an account.",["Navigate to the ZincBank website sign-up page","Enter a unique email address (e2e-<unique>@example.com)","Enter a valid password meeting the minimum requirements","Enter the user's name","Submit the sign-up form","Verify the account is created and the user is taken to the dashboard"],"Account is created and the user is signed in with a ready-to-use account showing a balance of 0.00 and an empty transaction history."],
  ["ZTM-4","A","A1-TC02: Account opening with missing required fields","negative","P1","ready","User is on the ZincBank sign-up page.",["Navigate to the ZincBank sign-up page","Leave the email, password and name fields empty","Submit the sign-up form","Verify validation errors are displayed for all required fields","Verify no account is created"],"The form is not submitted and a validation error is shown for each missing required field (email, password, name). No account is created."],
  ["ZTM-5","A","A1-TC03: Account opening with invalid email format","negative","P2","ready","User is on the ZincBank sign-up page.",["Navigate to the ZincBank sign-up page","Enter an invalid email address (e.g. 'not-an-email')","Enter a valid password and name","Submit the sign-up form","Verify a validation error is shown for the email field","Verify no account is created"],"The form is not submitted and a validation error is shown indicating the email address is invalid. No account is created."],
  ["ZTM-6","A","A1-TC04: Account opening with weak password","negative","P2","ready","User is on the ZincBank sign-up page.",["Navigate to the ZincBank sign-up page","Enter a valid email address and name","Enter a weak password (e.g. '123')","Submit the sign-up form","Verify a validation error is shown for the password field","Verify no account is created"],"The form is not submitted and a validation error is shown indicating the password does not meet the minimum strength/length requirements. No account is created."],
  ["ZTM-7","A","A2-TC01: Successful sign in with correct credentials","functional","P1","ready","A valid ZincBank account exists with known email and password.",["Navigate to the ZincBank sign-in page","Enter the correct email address","Enter the correct password","Submit the sign-in form","Verify the user is signed in and taken to the dashboard"],"The user is signed in and taken to their dashboard. The sign-in completes quickly without unnecessary steps."],
  ["ZTM-8","A","A2-TC02: Sign in with incorrect email","negative","P1","ready","A valid ZincBank account exists with a known password.",["Navigate to the ZincBank sign-in page","Enter an incorrect email address","Enter the correct password","Submit the sign-in form","Verify an error message is shown and the user is not signed in"],"The user is not signed in and an error message is shown indicating the email address is incorrect."],
  ["ZTM-9","A","A2-TC03: Sign in with incorrect password","negative","P1","ready","A valid ZincBank account exists with a known email address.",["Navigate to the ZincBank sign-in page","Enter the correct email address","Enter an incorrect password","Submit the sign-in form","Verify an error message is shown and the user is not signed in"],"The user is not signed in and an error message is shown indicating the password is incorrect."],
  ["ZTM-10","A","A2-TC04: Sign in with empty fields","negative","P2","ready","A valid ZincBank account exists.",["Navigate to the ZincBank sign-in page","Leave the email and/or password field empty","Submit the sign-in form","Verify a validation error is shown for the empty field(s)","Verify the user is not signed in"],"The user is not signed in and a validation error is shown for the empty field(s). No error is shown for the field that was filled correctly."],
  ["ZTM-11","A","A3-TC01: Sign up with an already-registered email","negative","P1","ready","An account already exists with the email address being used.",["Navigate to the ZincBank sign-up page","Enter an email address that already belongs to an existing account","Enter a valid password and name","Submit the sign-up form","Verify an error message is shown explaining the email is already in use","Verify the message directs the user to sign in instead","Verify no second account is created"],"The sign-up is rejected and an error message is shown explaining that the email address already belongs to an account, prompting the user to sign in instead. No second account is created."],
  ["ZTM-12","A","A3-TC02: Duplicate email detection is case-insensitive","boundary","P2","ready","An account already exists with the email address being used (e.g. user@example.com).",["Navigate to the ZincBank sign-up page","Enter the existing email address with different letter casing (e.g. USER@Example.com)","Enter a valid password and name","Submit the sign-up form","Verify the duplicate-email error message is shown","Verify no second account is created"],"The sign-up is rejected with the same duplicate-email error message regardless of case differences in the email address. No second account is created."],
  ["ZTM-13","A","A4-TC01: Reset password with a registered email","functional","P1","ready","A valid ZincBank account exists with a known email address.",["Navigate to the ZincBank sign-in page","Click the 'Forgot password' link","Enter the registered email address","Submit the reset request","Verify a confirmation message is shown","Verify a reset email is sent to the registered address","Follow the reset link and set a new password","Sign in with the new password and verify success"],"A password reset email is sent to the registered email address and a confirmation message is shown. The user can follow the link to set a new password and then sign in with it."],
  ["ZTM-14","A","A4-TC02: Reset password with an unregistered email","negative","P2","ready","No ZincBank account exists with the email address being used.",["Navigate to the ZincBank sign-in page","Click the 'Forgot password' link","Enter an email address that is not registered","Submit the reset request","Verify the system does not reveal whether the email exists","Verify no reset email is sent"],"The reset request is handled without revealing whether the email exists. No reset email is sent to an unregistered address and the user is not locked out of any account."],
  ["ZTM-15","A","A4-TC03: Reset link expires after validity period","security","P2","ready","A valid ZincBank account exists and a password reset email has been requested.",["Request a password reset for a registered email","Wait until the reset link's validity period has passed","Click the expired reset link","Verify the link is rejected and no password change is allowed","Verify the user must request a new reset link"],"The reset link is single-use and expires after the configured validity period. After expiry, the link no longer works and the user must request a new reset."],
  // MODULE B
  ["ZTM-16","B","B1-TC01: Customer sees all their accounts with balances","functional","P1","ready","A signed-in customer holds at least one checking and one savings account with known balances.",["Sign in to ZincBank","Navigate to the accounts overview page","Verify all accounts held by the customer are listed","Verify the accounts appear in a sensible order","Verify each account shows its current balance","Verify no accounts belonging to other customers are shown"],"The customer sees all accounts they hold, listed in a sensible order (e.g. checking first, then savings), each showing its current balance. No other customer's accounts are visible."],
  ["ZTM-17","B","B1-TC02: Only the customer's own accounts are shown","security","P1","ready","A signed-in customer exists and other customers with accounts exist in the system.",["Sign in to ZincBank as a customer","Navigate to the accounts overview page","Review every account listed","Verify each listed account belongs to the signed-in customer","Verify no other customer's account data is present in the response or UI"],"The accounts overview shows only the accounts belonging to the signed-in customer. No other customer's account names, numbers or balances are displayed."],
  ["ZTM-18","B","B1-TC03: Customer with no accounts sees empty state","boundary","P2","ready","A signed-in customer exists who holds no accounts.",["Sign in to ZincBank as a customer with no accounts","Navigate to the accounts overview page","Verify an empty state message is shown","Verify no error is displayed"],"A customer with no accounts sees an empty state message (e.g. 'No accounts yet') and is not shown any error. The page loads successfully."],
  ["ZTM-19","B","B2-TC01: Open an account and see payment details","functional","P1","ready","A signed-in customer holds at least one account.",["Sign in to ZincBank","Navigate to the accounts overview page","Tap/click one of the customer's accounts","Verify the account detail view opens","Verify the account name is shown","Verify the account number/IBAN is shown","Verify the sort code is shown","Verify the current balance is shown"],"Tapping an account opens its detail view showing the account name, account number/IBAN, sort code and current balance — the details needed to give to someone who wants to pay the customer."],
  ["ZTM-20","B","B2-TC02: Detail view shows the correct selected account","functional","P2","ready","A signed-in customer holds two or more accounts with different balances.",["Sign in to ZincBank","Navigate to the accounts overview page","Tap the first account and note its balance","Go back to the overview","Tap the second account","Verify the detail view shows the second account's data, not the first"],"The detail view shows the correct account's data matching the account that was tapped. The account number, sort code and balance correspond to the selected account, not another one."],
  ["ZTM-21","B","B3-TC01: Open an additional account self-service","functional","P1","ready","A signed-in customer holds at least one account and is on the accounts page.",["Sign in to ZincBank","Navigate to the accounts page","Select the option to open a new account","Choose an account type that is openable self-service (e.g. savings)","Confirm the new account","Verify the new account appears in the accounts list","Verify the new account has a balance of 0.00"],"A new account (e.g. savings) is opened self-service without calling the bank. The new account appears in the customer's accounts list with a balance of 0.00."],
  ["ZTM-22","B","B3-TC02: Non-self-service account types are not openable","negative","P2","ready","A signed-in customer is on the open-account flow.",["Sign in to ZincBank","Navigate to the open-account flow","Review the available account types","Verify account types not openable self-service are not offered or are disabled","Verify the customer cannot complete opening such an account"],"Account types that are not openable self-service (e.g. joint account) are not offered or are disabled in the open-account flow. The customer cannot open them without contacting the bank."],
  ["ZTM-23","B","B4-TC01: Direct access to another customer's account is denied","security","P1","ready","A signed-in customer exists and another customer's account exists whose ID/number is known to the first customer.",["Sign in to ZincBank as a customer","Attempt to navigate directly to another customer's account detail URL","Verify access is denied","Verify no account data is displayed","Verify the response does not reveal whether the account exists"],"Access to another customer's account is denied. The customer cannot see the account's data and cannot tell whether the account exists (no distinct 'not found' vs 'forbidden' message)."],
  ["ZTM-24","B","B4-TC02: API does not reveal whether another account exists","api","P2","ready","A signed-in customer exists, and both a non-existent account ID and another customer's account ID are known.",["Sign in to ZincBank and capture the session token","Call the account detail API with a non-existent account ID","Record the response status and body","Call the account detail API with another customer's account ID","Record the response status and body","Verify both responses are identical and do not reveal account existence"],"The API returns the same generic response (e.g. 404) for both a non-existent account and another customer's account, so the customer cannot distinguish between them."],
  // MODULE C
  ["ZTM-25","C","C1-TC01: Dashboard is the first thing shown after signing in","functional","P1","ready","A valid ZincBank account exists.",["Sign in to ZincBank","Verify the dashboard is shown as the first page","Verify a welcome message is displayed","Verify key information (accounts, balance) is visible at a glance"],"After signing in, the customer is taken to the dashboard which shows a welcome message. The dashboard loads quickly and shows key information at a glance."],
  ["ZTM-26","C","C2-TC01: Total deposit balance is shown at a glance","functional","P1","ready","A signed-in customer holds one or more accounts with known balances.",["Sign in to ZincBank","Navigate to the dashboard","Verify the total deposit balance is shown","Verify the total equals the sum of all account balances"],"The dashboard shows a single total deposit balance that equals the sum of all the customer's account balances."],
  ["ZTM-27","C","C3-TC01: Credit card is shown on the dashboard when present","functional","P2","ready","A signed-in customer exists; one with a credit card and one without.",["Sign in to ZincBank as a customer with a credit card","Navigate to the dashboard","Verify the card is shown on the dashboard","Sign in as a customer without a card","Verify no card section is shown"],"If the customer has a credit card, the dashboard shows it. If they do not have a card, no card section is shown."],
  ["ZTM-28","C","C4-TC01: Recent activity is shown on the dashboard","functional","P2","ready","A signed-in customer with recent transactions exists.",["Sign in to ZincBank","Navigate to the dashboard","Verify the recent activity section is shown","Verify transactions appear newest first","Verify only recent transactions are shown, not the full history"],"The dashboard shows recent activity, newest first, limited to recent transactions only (not the full history)."],
  ["ZTM-29","C","C5-TC01: Quick transfer shortcut is available on the dashboard","functional","P1","ready","A signed-in customer exists.",["Sign in to ZincBank","Navigate to the dashboard","Verify a quick transfer shortcut is present","Click the shortcut","Verify the customer is taken to the move money page"],"A shortcut to move money is present on the dashboard and clicking it takes the customer to the move money page."],
  // MODULE D
  ["ZTM-30","D","D1-TC01: Transfer money between own accounts","functional","P1","ready","A signed-in customer holds two accounts with sufficient funds.",["Sign in to ZincBank","Navigate to the move money page","Select the source account","Select the destination account","Enter an amount within the balance","Submit the transfer","Verify the source balance decreased and destination balance increased"],"Money is moved between the customer's own accounts. The source account balance decreases and the destination account balance increases by the same amount. The transfer is not allowed if there are insufficient funds."],
  ["ZTM-31","D","D2-TC01: Pay a company bill","functional","P1","ready","A signed-in customer with sufficient funds and a saved payee exists.",["Sign in to ZincBank","Navigate to the move money page","Select the pay a bill option","Select the source account","Select the payee","Enter the bill amount","Submit the payment","Verify the payment is completed and the account balance decreased"],"The bill payment is completed: the money leaves the customer's account and goes to the company. A confirmation is shown."],
  ["ZTM-32","D","D3-TC01: Add and remove payees from the list","functional","P2","ready","A signed-in customer exists.",["Sign in to ZincBank","Navigate to the move money page","Add a new payee with a name and account number","Verify the payee appears in the list","Attempt to add the same payee again","Verify the duplicate is not added","Remove the payee","Verify the payee is removed from the list"],"A payee can be added to the list and removed from it. The same payee cannot appear twice in the list."],
  ["ZTM-33","D","D4-TC01: Transfer with insufficient funds is blocked","negative","P1","ready","A signed-in customer holds an account with a known low balance.",["Sign in to ZincBank","Navigate to the move money page","Select the source account","Select the destination account","Enter an amount greater than the balance","Submit the transfer","Verify an INSUFFICIENT_FUNDS error is shown","Verify neither account balance changed"],"The transfer is blocked and an INSUFFICIENT_FUNDS error is shown. Neither account balance changes."],
  ["ZTM-34","D","D5-TC01: Pressing pay twice does not charge twice","security","P2","ready","A signed-in customer with sufficient funds exists.",["Sign in to ZincBank","Navigate to the move money page","Fill in a valid transfer","Click the submit button twice quickly","Verify only one transfer is recorded","Verify the account balance decreased only once"],"Pressing the pay/transfer button twice does not create a duplicate transaction. Only one transfer is recorded."],
  // MODULE F
  ["ZTM-35","F","F1-TC01: View and filter transaction history","functional","P1","ready","A signed-in customer with transactions on an account exists.",["Sign in to ZincBank","Navigate to the transactions page","Select an account","Verify the transaction history is shown","Apply a date range filter","Verify the transactions are filtered to that range","Verify the order makes sense (newest first)"],"The customer can view all transactions on an account and filter them by a date range. Transactions are shown in a sensible order (newest first)."],
  ["ZTM-36","F","F2-TC01: Long histories are paginated","functional","P2","ready","A signed-in customer with a long transaction history (more than one page) exists.",["Sign in to ZincBank","Navigate to the transactions page","Select an account with a long history","Verify the transactions are paginated","Navigate to the next page","Verify the next set of transactions is shown"],"Long transaction histories are broken up into pages so the list stays usable. The customer can navigate between pages."],
  ["ZTM-37","F","F3-TC01: Download a monthly statement","functional","P1","ready","A signed-in customer with an account that has a statement available exists.",["Sign in to ZincBank","Navigate to the transactions page","Select an account","Select a statement period","Download the statement","Verify the statement shows the period, opening balance, closing balance and transactions"],"A monthly statement can be downloaded for an account. It shows the period, opening balance, closing balance and all transactions in between, formatted like a bank statement."],
  ["ZTM-38","F","F4-TC01: Download a card statement","functional","P2","ready","A signed-in customer with a credit card exists.",["Sign in to ZincBank","Navigate to the cards page","Verify a statement download option is available","Download the card statement","Verify the statement covers the spending for the period"],"Credit card customers can download a statement covering what they spent in the period."],
  // MODULE G
  ["ZTM-39","G","G1-TC01: Apply for a credit card and get an immediate answer","functional","P1","ready","A signed-in customer without a credit card exists.",["Sign in to ZincBank","Navigate to the cards page","Fill in the card application form (income, employment, housing, debt)","Submit the application","Verify an immediate decision is shown","Apply again with the same details","Verify the same decision is returned"],"The customer can apply for a credit card from inside the app and receives an immediate decision. The same applicant always gets the same answer."],
  ["ZTM-40","G","G2-TC01: Approved customer sees card limit and APR","functional","P1","ready","A signed-in customer with an approved credit card exists.",["Sign in to ZincBank","Navigate to the cards page","Verify the card is shown","Verify the credit limit is displayed","Verify the APR is displayed","Verify the available credit is displayed"],"An approved customer sees their card with a spending limit and an interest rate (APR). Better applicants get better terms."],
  ["ZTM-41","G","G3-TC01: Spending on the card increases the amount owed","functional","P2","ready","A signed-in customer with an approved credit card exists.",["Sign in to ZincBank","Navigate to the cards page","Note the current balance owed","Make a purchase with the card","Verify the balance owed increased by the purchase amount","Attempt to spend past the credit limit","Verify the spending is blocked"],"When the customer spends on the card, the amount owed increases by that amount. The customer cannot spend past their credit limit."],
  ["ZTM-42","G","G4-TC01: Pay the card from the current account","functional","P1","ready","A signed-in customer with a credit card that has a balance owed exists.",["Sign in to ZincBank","Navigate to the cards page","Select the account to pay from","Enter an amount to pay","Submit the payment","Verify the amount owed decreased","Verify the account balance decreased to match","Attempt to pay more than owed","Verify the overpayment is blocked"],"The customer can pay their card from their current account. The amount owed decreases and the account balance decreases to match. The customer cannot pay more than they owe."],
  ["ZTM-43","G","G5-TC01: Download the card statement","functional","P2","ready","A signed-in customer with a credit card exists.",["Sign in to ZincBank","Navigate to the cards page","Download the card statement","Verify the statement shows the amount owed","Verify the minimum payment is shown","Verify the due date is shown","Verify the full card number is not printed"],"The customer gets a monthly statement showing what they owe, the minimum payment and the due date. It can be downloaded and does not print the full card number."],
  ["ZTM-44","G","G6-TC01: Customer with a card cannot get a second one","negative","P2","ready","A signed-in customer with an existing credit card exists.",["Sign in to ZincBank","Navigate to the cards page","Verify the customer already has a card","Attempt to apply for another card","Verify the customer is told they already have a card","Verify no second card is created"],"A customer can have only one credit card. If they already have one and apply again, they are told they already have a card."],
  // MODULE H
  ["ZTM-45","H","H1-TC01: See personal details","functional","P1","ready","A signed-in customer exists.",["Sign in to ZincBank","Navigate to the profile page","Verify the personal details are shown (first name, last name, phone, address, email)"],"The customer can view the personal details the bank holds for them (name, phone, address, email)."],
  ["ZTM-46","H","H2-TC01: Change personal details but not email","functional","P1","ready","A signed-in customer exists.",["Sign in to ZincBank","Navigate to the profile page","Update the phone number","Save the changes","Verify the phone number is updated","Attempt to change the email address","Verify the email field is disabled and cannot be changed"],"The customer can update their phone number and address without calling the bank. The email address cannot be changed by the customer."],
  ["ZTM-47","H","H3-TC01: Change the password","functional","P1","ready","A signed-in customer exists with a known current password.",["Sign in to ZincBank","Navigate to the profile page","Enter the current password","Enter a new password","Submit the change","Sign out","Sign in with the new password","Verify the sign-in succeeds"],"The customer can change their password after confirming their current password. The new password takes effect on the next sign-in."],
  ["ZTM-48","H","H4-TC01: Signed-in access vs signed-out redirect","security","P1","ready","A valid account exists and a signed-out visitor state is available.",["Sign in to ZincBank","Verify the customer can access the dashboard and accounts","Sign out","Attempt to access the dashboard directly","Verify the visitor is redirected to the login page","Attempt to access the accounts page directly","Verify the visitor is redirected to the login page"],"A signed-in customer can access their own private pages. A visitor who is not signed in cannot access any private page and is redirected to the login page."],
  ["ZTM-49","H","H5-TC01: Friendly error message on failure","negative","P2","ready","A signed-in customer exists and a failure scenario can be triggered (e.g. invalid input).",["Sign in to ZincBank","Trigger a failure scenario (e.g. invalid input or insufficient funds)","Verify a plain-language error message is shown","Verify the message explains what happened","Verify the message explains what to do","Verify no technical error details are shown"],"When something fails, the customer sees a plain-language error message explaining what happened and what to do, instead of a technical error."],
];

const modules = {
  A: "Getting Started",
  B: "Your Accounts",
  C: "Your Money at a Glance",
  D: "Moving Money",
  F: "Statements and History",
  G: "Credit Card",
  H: "Your Details and Security",
};

const typeClass = {
  functional: "t-functional",
  negative: "t-negative",
  boundary: "t-boundary",
  security: "t-security",
  api: "t-api",
};

function esc(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function row(c) {
  const steps = c[7].map((s) => `<li>${esc(s)}</li>`).join("");
  return `<tr><td class="key">${c[0]}</td><td>${esc(c[2])}</td><td><span class="tag ${typeClass[c[3]]}">${c[3]}</span> <span class="tag p-${c[4]}">${c[4]}</span> <span class="tag st-ready">${c[5]}</span></td><td class="pre">${esc(c[6])}</td><td><ol>${steps}</ol></td><td><div class="expected">${esc(c[8])}</div></td></tr>`;
}

let html = `<!DOCTYPE html>
<html lang="tr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ZincBank Test Case Raporu</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', Arial, sans-serif; background: #f4f6f9; color: #1a1a2e; padding: 24px; }
  h1 { font-size: 26px; margin-bottom: 4px; }
  .subtitle { color: #666; margin-bottom: 20px; }
  .summary { display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 24px; }
  .card { background: #fff; border-radius: 10px; padding: 16px 20px; box-shadow: 0 1px 4px rgba(0,0,0,.08); flex: 1; min-width: 130px; }
  .card .num { font-size: 28px; font-weight: 700; color: #0f4c81; }
  .card .lbl { color: #666; font-size: 13px; }
  .mod { background: #fff; border-radius: 10px; box-shadow: 0 1px 4px rgba(0,0,0,.08); margin-bottom: 20px; overflow: hidden; }
  .mod-head { background: #0f4c81; color: #fff; padding: 12px 20px; font-weight: 600; }
  .mod-head .ref { background: rgba(255,255,255,.2); padding: 2px 8px; border-radius: 4px; margin-right: 8px; }
  table { width: 100%; border-collapse: collapse; }
  th, td { text-align: left; padding: 10px 16px; border-bottom: 1px solid #eef0f4; font-size: 13px; vertical-align: top; }
  th { background: #fafbfc; color: #555; font-size: 12px; text-transform: uppercase; letter-spacing: .4px; }
  .key { font-weight: 700; color: #0f4c81; white-space: nowrap; }
  .tag { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; margin: 1px 2px 1px 0; }
  .t-functional { background: #e3f2e3; color: #1b5e20; }
  .t-negative { background: #fdecea; color: #b71c1c; }
  .t-boundary { background: #fff3e0; color: #e65100; }
  .t-security { background: #ede7f6; color: #4527a0; }
  .t-api { background: #e0f2f1; color: #00695c; }
  .p-P1 { background: #fdecea; color: #b71c1c; }
  .p-P2 { background: #fff8e1; color: #f57f17; }
  .st-ready { background: #e3f2e3; color: #1b5e20; }
  ol { margin-left: 18px; }
  ol li { margin-bottom: 2px; }
  .expected { background: #f0f7f0; border-left: 3px solid #2e7d32; padding: 8px 12px; border-radius: 0 6px 6px 0; }
  .pre { color: #555; font-style: italic; }
</style>
</head>
<body>
  <h1>ZincBank — Test Case Raporu</h1>
  <div class="subtitle">Tüm Modüller · Oluşturulma: 2026-08-23</div>
  <div class="summary">
    <div class="card"><div class="num">7</div><div class="lbl">Modül</div></div>
    <div class="card"><div class="num">${cases.length}</div><div class="lbl">Test Case</div></div>
  </div>
`;

for (const [code, name] of Object.entries(modules)) {
  const modCases = cases.filter((c) => c[1] === code);
  if (modCases.length === 0) continue;
  html += `<div class="mod"><div class="mod-head"><span class="ref">${code}</span>${name}</div><table><tr><th>Key</th><th>Başlık</th><th>Tip</th><th>Ön Koşul</th><th>Adımlar</th><th>Beklenen Sonuç</th></tr>`;
  html += modCases.map(row).join("");
  html += `</table></div>`;
}

html += `</body></html>`;

fs.writeFileSync("test-cases-report.html", html, "utf8");
console.log("HTML report generated: test-cases-report.html (" + cases.length + " test cases)");
